# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Francisco Lopez Sanchez
title: Sofware Engineer
email: francisco.lopsan@gmail.com
email_title: "mail"

# Dark Mode (true/false/never)
darkmode: false

github_username: franciscolopezsanchez

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
gtag: "G-JD1532W65J"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I'm a passionate software engineer dedicated to crafting enchanting **user experiences**. With a focus on pixel perfection and user delight, I communicate fluently, collaborating seamlessly in the symphony of coding. A perpetual learner and tech explorer, constantly venturing into new horizons in technology.

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: femtasy
        sub_title: Full-Stack Engineer
        caption: January 2020 - August 2023
        quote: >
          remote - Germany
        description: | # this will include new lines to allow paragraphs
          Led the design and execution of an audio recommendation system utilizing <mark>AWS Personalize</mark>. The personalized recommended audio lists demonstrated superior performance compared to static lists throughout the application.

          Collaborated in the design and implementation of a system utilizing <mark>Strapi</mark> and <mark>Next.js</mark>, enabling brand team to independently craft dynamic marketing pages. This approach granted them the autonomy to construct pages with essential components without requiring developer assistance.

          Played a key role in the post-migration phase of our API from Rails to Elixir, actively contributing to the rewriting of frontend <mark>React.js</mark> components and in the <mark>React Native</mark> app. Utilized <mark>GraphQL</mark> with Apollo and <mark>Typescript</mark> to enhance system efficiency and maintain code integrity.
      - layout: left
        title: Derivco UK
        sub_title: Team Lead
        caption: January 2015 - July 2019
        quote: >
          Ipswich (UK) - Barcelona (Spain)
        description: | # this will include new lines to allow paragraphs
          Led a team of 5 engineers and 4 QAs, concurrently serving as a Scrum Master.

          Responsibilities encompassed <mark>coaching</mark> new team members, overseeing career development, conducting performance reviews and actively participating in recruitment and <mark>interviews</mark>.
      - layout: left
        title: Derivco UK
        sub_title: Sofware Engineer
        caption: May 2013 - January 2015
        quote: >
          Ipswich (UK)
        description: |
          Focused on Front-end development, dedicated to creating exceptional <mark>user interfaces</mark> with a commitment to achieving <mark>pixel-perfect</mark> precision.

  - title: Projects
    layout: list
    content:
      - layout: left
        title: Escapeitor & TuPistaLibre
        caption: 2017 / 2015
        description: |
          Teamed up with two university colleagues for both projects. Primarily focusing on the front-end components, including both the web application and admin UI using <mark>JS</mark> (Angular), <mark>HTML</mark> and <mark>CSS</mark>.

  - title: Education
    layout: list
    content:
      - layout: left
        title: Computer Science Degree
        sub_title: University of Seville
        caption: 2006 - 2012

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Passionate about exploring and mastering various sports, I consider myself a dedicated **sport-tester**. Currently focused on rock climbing, I actively seek new challenges. Beyond sports, I have a deep love for travel and mountain hikes. Having conquered a couple of volcanos in Central America and the 4k+ meters Toubkal mountain in Morocco, I find joy in pushing my physical limits. On weekends, you'll often find me on the road with my van, partner, and recently adopted dog, exploring Andalucian rocks in search of our next climbing adventure.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

exclude:
  [
    "Gemfile",
    "Gemfile.lock",
    "node_modules",
    "vendor/bundle/",
    "vendor/cache/",
    "vendor/gems/",
    "vendor/ruby/",
    "lib/",
    "scripts/",
    "docker-compose.yml",
  ]
